local-phone-apps :=  \
			ApplicationsProvider \
			BackupRestoreConfirmation \
			Bluetooth \
			BluetoothServices \
			CertInstaller \
			DefaultContainerService \
			DolbyMobileAudioEffectService \
			DrmProvider \
			FaceLock \
			FmService \
			HTMLViewer \
			HwBluetoothImport \
			HwCamera \
			HwFMRadio \
			HwWiFiHotspot \
			KeyChain \
			LiveWallpapers \
			LiveWallpapersPicker \
			MediaCenter \
			MediaProvider \
			OMACP \
			PicoTts \
			PowerManagement \
			Settings_ex \
			SettingsProvider \
			SharedStorageBackup \
			StockSettings \
			UserDictionaryProvider \
			VisualizationWallpapers \
			VoiceDialer \
			VpnDialogs \
			WAPPushManager 
